### ISSUE TITLE
payment

### ISSUE THREAD

**Issue by kowshikjawad** [perceptronbd/rouge-tactical#123]
- [x] controller to add services
- [x] controller to update(edit/delete) services
- [x] filter controller: calculates the total cost according to filter based on due date for each service
- [ ] filter controller: calculates the totalAmount and depositedAmount according to filter based on updatedAt for all the invoices

**Comment by asif-bhuti** [comment]
the response data for invoice should look something like this 
`
data = {
  depositedAmount : depositedAmount,
  dueAmount: totalAmount - depositedAmount
}
`
